# Rust formatting configuration
edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Auto"
use_small_heuristics = "Default"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
blank_lines_upper_bound = 1
blank_lines_lower_bound = 0
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"
trailing_semicolon = true
trailing_comma = "Vertical"
match_arm_leading_pipes = "Never"
match_arm_blocks = false
match_block_trailing_comma = false
combine_control_expr = true
overflow_delimited_expr = false
space_before_colon = false
space_after_colon = true
spaces_around_ranges = false
indent_style = "Block"
normalize_comments = false
normalize_doc_attributes = false
license_template_path = ""
format_generated_files = false
format_macro_bodies = true
format_macro_matchers = false
format_strings = false
empty_item_single_line = true
struct_lit_single_line = true
fn_single_line = false
where_single_line = false
imports_indent = "Block"
imports_layout = "Mixed"
merge_imports = false
normalize_comments = false
wrap_comments = false
comment_width = 80
condense_wildcard_suffixes = false
use_field_init_shorthand = false
force_multiline_blocks = false
fn_args_layout = "Tall"
type_punctuation_density = "Wide"
dense_array = true
dense_struct = true
overflow_delimited_expr = false
struct_field_align_threshold = 0
enum_discrim_align_threshold = 0
match_arm_leading_pipes = "Never"
force_explicit_abi = true
imports_granularity = "Preserve"